"""compteur de commandes

Revision ID: 27664c4b24cc
Revises: bed4ef38229c
Create Date: 2026-08-15 20:05:02.383211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27664c4b24cc'
down_revision: Union[str, Sequence[str], None] = 'bed4ef38229c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('command_seq', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'command_seq')
    # ### end Alembic commands ###
