"""sessions et file partagee

Revision ID: 354b17eb8528
Revises: b39317a0259c
Create Date: 2026-08-15 19:51:26.375344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354b17eb8528'
down_revision: Union[str, Sequence[str], None] = 'b39317a0259c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('output_mode', sa.String(length=16), nullable=False),
    sa.Column('snapcast_stream_id', sa.String(length=100), nullable=True),
    sa.Column('snapcast_port', sa.Integer(), nullable=True),
    sa.Column('current_item_id', sa.Integer(), nullable=True),
    sa.Column('is_playing', sa.Boolean(), nullable=False),
    sa.Column('position_s', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=60), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_items_session_position', 'queue_items', ['session_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queue_items_session_position', table_name='queue_items')
    op.drop_table('queue_items')
    op.drop_table('sessions')
    # ### end Alembic commands ###
