"""retrait du mode de sortie par session

Revision ID: 585d6ce1c9e5
Revises: 27664c4b24cc
Create Date: 2026-08-16 17:59:26.780195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '585d6ce1c9e5'
down_revision: Union[str, Sequence[str], None] = '27664c4b24cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'output_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('output_mode', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
