"""schema initial

Revision ID: 93cfe96471b6
Revises: 
Create Date: 2026-08-15 17:49:38.745789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cfe96471b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mbid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ft_artists_name', 'artists', ['name'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('files_seen', sa.Integer(), nullable=False),
    sa.Column('files_indexed', sa.Integer(), nullable=False),
    sa.Column('files_removed', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('source_title', sa.String(length=255), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mbid', sa.String(length=36), nullable=True),
    sa.Column('cover_file', sa.String(length=255), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ft_albums_title', 'albums', ['title'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('uq_albums_artist_source_title', 'albums', ['artist_id', 'source_title'], unique=True)
    op.create_table('scan_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('source_title', sa.String(length=255), nullable=False),
    sa.Column('source_track_no', sa.Integer(), nullable=True),
    sa.Column('source_disc_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('track_no', sa.Integer(), nullable=True),
    sa.Column('disc_no', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('object_key_hash', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key_hash')
    )
    op.create_index('ft_tracks_title', 'tracks', ['title'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ft_tracks_title', table_name='tracks', mysql_prefix='FULLTEXT')
    op.drop_table('tracks')
    op.drop_table('scan_errors')
    op.drop_index('uq_albums_artist_source_title', table_name='albums')
    op.drop_index('ft_albums_title', table_name='albums', mysql_prefix='FULLTEXT')
    op.drop_table('albums')
    op.drop_table('scan_runs')
    op.drop_index('ft_artists_name', table_name='artists', mysql_prefix='FULLTEXT')
    op.drop_table('artists')
    # ### end Alembic commands ###
