"""genre et paroles

Revision ID: b39317a0259c
Revises: 93cfe96471b6
Create Date: 2026-08-15 18:50:16.509559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39317a0259c'
down_revision: Union[str, Sequence[str], None] = '93cfe96471b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('tracks', sa.Column('lyrics', sa.Text(), nullable=True))
    op.create_index('ix_tracks_genre', 'tracks', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracks_genre', table_name='tracks')
    op.drop_column('tracks', 'lyrics')
    op.drop_column('tracks', 'genre')
    # ### end Alembic commands ###
